name: Build and publish wheels

on:
  release:
    types: [published]

jobs:
  build-publish:
    name: Build manylinux wheels and publish to PyPI
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install Docker (if needed)
        run: sudo apt-get update && sudo apt-get install -y docker.io

      - name: Build manylinux wheels
        run: |
          docker run --rm -v ${{ github.workspace }}:/io ghcr.io/pyo3/maturin build \
            --release \
            --manylinux 2014 \
            --interpreter python3.7 \
            --interpreter python3.8 \
            --interpreter python3.9 \
            --interpreter python3.10 \
            --interpreter python3.11 \
            --interpreter python3.12

      - name: Publish wheels to PyPI
        run: |
          pip install twine
          twine upload --skip-existing --username __token__ --password ${{ secrets.PYPI_API_TOKEN }} target/wheels/*.whl
