name: Build and Publish to PyPI

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [x86_64]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Maturin
        run: pip install maturin

      - name: Build manylinux wheel
        run: |
          maturin build --release --manylinux 2014

      - name: Upload to PyPI
        env:
          MATURIN_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          maturin publish --username __token__ --password $MATURIN_PASSWORD --skip-existing
